// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhpr8zjoOJKjbOrifHGQaqSDETSgAYKH0',
    appId: '1:649635464500:web:ec447b6ed4898594145161',
    messagingSenderId: '649635464500',
    projectId: 'expense-tr-f6f11',
    authDomain: 'expense-tr-f6f11.firebaseapp.com',
    storageBucket: 'expense-tr-f6f11.firebasestorage.app',
    measurementId: 'G-3RN97VLDR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHzi5HbANkoeLWXSUO0AeZ7Qm7CHf60L8',
    appId: '1:649635464500:android:d50a67b3bc7163c7145161',
    messagingSenderId: '649635464500',
    projectId: 'expense-tr-f6f11',
    storageBucket: 'expense-tr-f6f11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwjFc0NdBFvms6Syr_lO6CFFa5AYO15FI',
    appId: '1:649635464500:ios:0d22db9807cbaddb145161',
    messagingSenderId: '649635464500',
    projectId: 'expense-tr-f6f11',
    storageBucket: 'expense-tr-f6f11.firebasestorage.app',
    androidClientId: '649635464500-oo8tmpcl9fq6lcvu8s0ve6arnbt3n8ke.apps.googleusercontent.com',
    iosClientId: '649635464500-ois07nlr5031jj730ncg8n8q5trs1nh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwjFc0NdBFvms6Syr_lO6CFFa5AYO15FI',
    appId: '1:649635464500:ios:0d22db9807cbaddb145161',
    messagingSenderId: '649635464500',
    projectId: 'expense-tr-f6f11',
    storageBucket: 'expense-tr-f6f11.firebasestorage.app',
    androidClientId: '649635464500-oo8tmpcl9fq6lcvu8s0ve6arnbt3n8ke.apps.googleusercontent.com',
    iosClientId: '649635464500-ois07nlr5031jj730ncg8n8q5trs1nh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhpr8zjoOJKjbOrifHGQaqSDETSgAYKH0',
    appId: '1:649635464500:web:f07a18d97d862ae8145161',
    messagingSenderId: '649635464500',
    projectId: 'expense-tr-f6f11',
    authDomain: 'expense-tr-f6f11.firebaseapp.com',
    storageBucket: 'expense-tr-f6f11.firebasestorage.app',
    measurementId: 'G-XELYHZF5BC',
  );
}
